using System;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Threading;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.AspNetCore.Razor.Language.Intermediate;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using RazorBlade.Analyzers.Support;

namespace RazorBlade.Analyzers;

internal static class BuildTimeTemplateRunner
{
    private const string _baseClassName = "RazorBlade.CSharpGenerator";

    public static string? TryGenerate(RazorCodeDocument? codeDocument, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var primaryClass = codeDocument?.GetDocumentIntermediateNode()?.FindPrimaryClass();
        if (primaryClass?.BaseType is not _baseClassName)
            return null;

        var fullClassName = codeDocument?.GetDocumentIntermediateNode()?.FindPrimaryNamespace()?.Content is { } primaryNamespace
            ? $"{primaryNamespace}.{primaryClass.ClassName}"
            : primaryClass.ClassName;

        var generatorCode =
            // language=csharp
            $$"""
            // <auto-generated/>

            namespace RazorBlade
            {
                internal abstract class CSharpGenerator : global::RazorBlade.PlainTextTemplate
                {
                    private static string Run()
                    {
                        return new global::{{fullClassName}}().Render();
                    }
                }
            }

            """;

        var peStream = new MemoryStream();
        var runtimeDir = Path.GetDirectoryName(typeof(object).Assembly.Location)!;

        // TODO: Handle errors

        var emitResult = CSharpCompilation.Create("RazorBladeScript")
                                          .AddReferences(
                                              MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                                              MetadataReference.CreateFromFile(Path.Combine(runtimeDir, "netstandard.dll"))
                                          )
                                          .AddSyntaxTrees([
                                              CSharpSyntaxTree.ParseText(
                                                  codeDocument.GetCSharpDocument().GeneratedCode,
                                                  cancellationToken: cancellationToken
                                              ),
                                              CSharpSyntaxTree.ParseText(
                                                  generatorCode,
                                                  cancellationToken: cancellationToken
                                              ),
                                              ..EmbeddedLibrarySourceGenerator.GetSyntaxTrees(null, cancellationToken)
                                          ])
                                          .WithOptions(new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary).WithNullableContextOptions(NullableContextOptions.Enable))
                                          .Emit(peStream, cancellationToken: cancellationToken);

        if (!emitResult.Success)
            return string.Empty;

        peStream.Position = 0;

        using var assemblyLoader = AssemblyLoader.Create();
        var assembly = assemblyLoader.LoadFromStream(peStream);

        return assembly.GetType(_baseClassName)
                       .EnsureNotNull($"Could not find type {_baseClassName} in generated assembly")
                       .GetMethod("Run", BindingFlags.NonPublic | BindingFlags.Static)
                       .EnsureNotNull("Could not find expected method in generated assembly")
                       .Invoke(null, [])
                       .EnsureNotNull("The build-time template returned null.") as string;
    }

    private abstract class AssemblyLoader : IDisposable
    {
        private static readonly Type? _alcType = Type.GetType("System.Runtime.Loader.AssemblyLoadContext, System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", false);

        public static AssemblyLoader Create()
            => _alcType is not null
                ? new AlcAssemblyLoader()
                : new FrameworkAssemblyLoader();

        public abstract void Dispose();
        public abstract Assembly LoadFromStream(MemoryStream peStream);

        private class AlcAssemblyLoader : AssemblyLoader
        {
            private static readonly MethodInfo _loadFromStream;
            private static readonly MethodInfo _unload;

            private object? _alc;

            static AlcAssemblyLoader()
            {
                Debug.Assert(_alcType is not null);

                _loadFromStream = _alcType?.GetMethod("LoadFromStream", BindingFlags.Instance | BindingFlags.Public, null, [typeof(Stream)], null)
                                  ?? throw new InvalidOperationException("Could not find AssemblyLoadContext.LoadFromStream method.");

                _unload = _alcType.GetMethod("Unload", BindingFlags.Instance | BindingFlags.Public, null, [], null)
                          ?? throw new InvalidOperationException("Could not find AssemblyLoadContext.Unload method.");
            }

            public AlcAssemblyLoader()
            {
                Debug.Assert(_alcType is not null);

                _alc = Activator.CreateInstance(_alcType, null, true)
                                .EnsureNotNull("Could not create AssemblyLoadContext.");
            }

            public override Assembly LoadFromStream(MemoryStream peStream)
                => _loadFromStream.Invoke(_alc.EnsureNotNull("AssemblyLoadContext is not available"), [peStream]) as Assembly
                   ?? throw new InvalidOperationException("Could not load generated assembly.");

            public override void Dispose()
            {
                _unload.Invoke(_alc, []);
                _alc = null;
            }
        }

        private class FrameworkAssemblyLoader : AssemblyLoader
        {
            public override Assembly LoadFromStream(MemoryStream peStream)
            {
                Debug.Assert(RuntimeInformation.FrameworkDescription.StartsWith(".NET Framework", StringComparison.Ordinal));

                return Assembly.Load(peStream.ToArray());
            }

            public override void Dispose()
            {
            }
        }
    }
}
