using System.IO;
using System.Reflection;
using System.Threading;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.AspNetCore.Razor.Language.Intermediate;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Scripting.Hosting;

namespace RazorBlade.Analyzers;

internal static class BuildTimeTemplateRunner
{
    private const string _baseClassName = "RazorBlade.CSharpGenerator";

    public static string? TryGenerate(RazorCodeDocument? codeDocument, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var primaryClass = codeDocument?.GetDocumentIntermediateNode()?.FindPrimaryClass();
        if (primaryClass?.BaseType is not _baseClassName)
            return null;

        var fullClassName = codeDocument?.GetDocumentIntermediateNode()?.FindPrimaryNamespace()?.Content is { } primaryNamespace
            ? $"{primaryNamespace}.{primaryClass.ClassName}"
            : primaryClass.ClassName;

        var generatorCode =
            // language=csharp
            $$"""
            // <auto-generated/>

            namespace RazorBlade
            {
                internal abstract class CSharpGenerator : global::RazorBlade.PlainTextTemplate
                {
                    private static string Run()
                    {
                        return new global::{{fullClassName}}().Render();
                    }
                }
            }

            """;

        var peStream = new MemoryStream();
        var runtimeDir = Path.GetDirectoryName(typeof(object).Assembly.Location)!;

        // TODO: Handle errors

        var emitResult = CSharpCompilation.Create("RazorBladeScript")
                                          .AddReferences(
                                              MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                                              MetadataReference.CreateFromFile(Path.Combine(runtimeDir, "netstandard.dll"))
                                          )
                                          .AddSyntaxTrees([
                                              CSharpSyntaxTree.ParseText(
                                                  codeDocument.GetCSharpDocument().GeneratedCode,
                                                  cancellationToken: cancellationToken
                                              ),
                                              CSharpSyntaxTree.ParseText(
                                                  generatorCode,
                                                  cancellationToken: cancellationToken
                                              ),
                                              ..EmbeddedLibrarySourceGenerator.GetSyntaxTrees(null, cancellationToken)
                                          ])
                                          .WithOptions(new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary).WithNullableContextOptions(NullableContextOptions.Enable))
                                          .Emit(peStream, cancellationToken: cancellationToken);

        if (!emitResult.Success)
            return string.Empty;

        peStream.Position = 0;

        // TODO: Remove dependency on the Scripting assemblies

        using var publicLoader = new InteractiveAssemblyLoader();

        var loaderField = typeof(InteractiveAssemblyLoader).GetField("_runtimeAssemblyLoader", BindingFlags.NonPublic | BindingFlags.Instance)!;
        var loader = loaderField.GetValue(publicLoader);

        var assembly = (Assembly)loaderField.FieldType
                                            .GetMethod("LoadFromStream", BindingFlags.Instance | BindingFlags.Public)!
                                            .Invoke(loader, [peStream, null]);

        return assembly.GetType(_baseClassName)!
                       .GetMethod("Run", BindingFlags.NonPublic | BindingFlags.Static)!
                       .Invoke(null, []) as string;
    }
}
