using System;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.AspNetCore.Razor.Language.CodeGeneration;
using Microsoft.AspNetCore.Razor.Language.Intermediate;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using RazorBlade.Analyzers.Support;
using SyntaxKind = Microsoft.CodeAnalysis.CSharp.SyntaxKind;

namespace RazorBlade.Analyzers;

internal class LibraryCodeGenerator
{
    private static readonly SymbolDisplayFormat _paramSignatureFormat
        = new(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            memberOptions: SymbolDisplayMemberOptions.IncludeContainingType, // For enums
            parameterOptions: SymbolDisplayParameterOptions.IncludeName
                              | SymbolDisplayParameterOptions.IncludeType
                              | SymbolDisplayParameterOptions.IncludeParamsRefOut
                              | SymbolDisplayParameterOptions.IncludeDefaultValue,
            miscellaneousOptions: SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers
                                  | SymbolDisplayMiscellaneousOptions.UseSpecialTypes
                                  | SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier
        );

    private readonly RazorCSharpDocument _generatedDoc;
    private readonly Compilation _inputCompilation;
    private readonly CSharpParseOptions _parseOptions;
    private readonly ImmutableArray<SyntaxTree> _additionalSyntaxTrees;
    private readonly CodeWriter _writer;
    private bool _hasCode;

    private INamedTypeSymbol? _classSymbol;
    private Compilation _compilation;
    private SemanticModel? _semanticModel;
    private ClassDeclarationSyntax? _classDeclarationSyntax;

    public LibraryCodeGenerator(RazorCSharpDocument generatedDoc,
                                Compilation compilation,
                                CSharpParseOptions parseOptions,
                                ImmutableArray<SyntaxTree> additionalSyntaxTrees)
    {
        _generatedDoc = generatedDoc;
        _inputCompilation = compilation;
        _parseOptions = parseOptions;
        _additionalSyntaxTrees = additionalSyntaxTrees;

        _compilation = _inputCompilation;
        _writer = new CodeWriter(Environment.NewLine, generatedDoc.Options);
    }

    public string Generate(CancellationToken cancellationToken)
    {
        Analyze(cancellationToken);

        if (_classSymbol is not null)
        {
            _writer.WriteLine("// <auto-generated/>");
            _writer.WriteLine();

            if (!_generatedDoc.Options.SuppressNullabilityEnforcement)
            {
                _writer.WriteLine("#nullable restore");
                _writer.WriteLine();
            }

            using (_writer.BuildNamespace(_classSymbol.ContainingNamespace.ToDisplayString()))
            using (_writer.BuildClassDeclaration(
                       ["partial"],
                       _classSymbol.Name,
                       null,
                       [],
                       _classSymbol.TypeParameters.Select(param => new TypeParameter { ParameterName = param.Name }).ToList(),
                       useNullableContext: false
                   ))
            {
                GenerateConstructors();
            }
        }

        return _hasCode ? _writer.GenerateCode() : string.Empty;
    }

    private void Analyze(CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();

        var syntaxTree = CSharpSyntaxTree.ParseText(
            _generatedDoc.GeneratedCode,
            _parseOptions,
            cancellationToken: cancellationToken
        );

        _compilation = _inputCompilation.WithOptions(_inputCompilation.Options.WithReportSuppressedDiagnostics(true))
                                        .AddSyntaxTrees(syntaxTree)
                                        .AddSyntaxTrees(_additionalSyntaxTrees);

        _semanticModel = _compilation.GetSemanticModel(syntaxTree);

        _classDeclarationSyntax = syntaxTree.GetRoot(cancellationToken)
                                            .DescendantNodes()
                                            .FirstOrDefault(static i => i.IsKind(SyntaxKind.ClassDeclaration)) as ClassDeclarationSyntax;

        _classSymbol = _classDeclarationSyntax is not null
            ? _semanticModel.GetDeclaredSymbol(_classDeclarationSyntax, cancellationToken)
            : null;
    }

    private void GenerateConstructors()
    {
        if (_classSymbol?.BaseType is not { } baseType)
            return;

        var templateCtorAttribute = _compilation.GetTypeByMetadataName("RazorBlade.Support.TemplateConstructorAttribute");
        if (templateCtorAttribute is null)
            return;

        var templateCtors = _classSymbol.InstanceConstructors;

        foreach (var ctor in baseType.InstanceConstructors)
        {
            if (!ctor.HasAttribute(templateCtorAttribute))
                continue;

            if (!_compilation.IsSymbolAccessibleWithin(ctor, _classSymbol))
                continue;

            if (templateCtors.Any(defCtor => RoslynHelper.AreParameterTypesEqual(defCtor.Parameters, ctor.Parameters)))
                continue;

            StartMember();

            WriteInheritDoc(ctor);

            _writer.Write("public ")
                   .Write(_classSymbol!.Name);

            WriteParametersSignature(ctor);
            _writer.WriteLine();

            using (_writer.IndentScope())
            {
                _writer.Write(": base");
                WriteParametersCall(ctor);
                _writer.WriteLine();
            }

            _writer.WriteLine("{")
                   .WriteLine("}");
        }
    }

    private void StartMember()
    {
        if (_hasCode)
            _writer.WriteLine();
        else
            _hasCode = true;
    }

    private void WriteInheritDoc(ISymbol symbol)
    {
        var cref = DocumentationCommentId.CreateDeclarationId(symbol.OriginalDefinition);
        if (string.IsNullOrEmpty(cref))
            return;

        // Work around https://youtrack.jetbrains.com/issue/RIDER-84751
        if (cref.IndexOf('~') is >= 0 and var index)
            cref = cref.Substring(0, index);

        _writer.WriteLine($"""/// <inheritdoc cref="{cref}" />""");
    }

    private void WriteParametersSignature(IMethodSymbol methodSymbol)
    {
        _writer.Write("(");

        foreach (var param in methodSymbol.Parameters)
        {
            if (param.Ordinal != 0)
                _writer.WriteParameterSeparator();

            _writer.Write(param.ToDisplayString(_paramSignatureFormat));
        }

        _writer.Write(")");
    }

    private void WriteParametersCall(IMethodSymbol methodSymbol)
    {
        _writer.Write("(");

        foreach (var param in methodSymbol.Parameters)
        {
            if (param.Ordinal != 0)
                _writer.WriteParameterSeparator();

            _writer.Write(param.RefKind switch
            {
                RefKind.Ref => "ref ",
                RefKind.Out => "out ",
                RefKind.In  => "in ",
                _           => string.Empty
            });

            _writer.Write(param.Name.EscapeCSharpKeyword());
        }

        _writer.Write(")");
    }
}
