using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using RazorBlade.Analyzers.Support;
using RazorBlade.MetaAnalyzers.Support;

namespace RazorBlade.MetaAnalyzers;

[Generator]
public class ResourcesSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var inputFiles = context.AdditionalTextsProvider
                                .Where(i => i.Path.EndsWith(".resx", StringComparison.OrdinalIgnoreCase))
                                .Combine(context.AnalyzerConfigOptionsProvider)
                                .Select(static (pair, _) =>
                                {
                                    var (additionalText, analyzerConfigOptions) = pair;
                                    var options = analyzerConfigOptions.GetOptions(additionalText);

                                    options.TryGetValue("build_metadata.AdditionalFiles.Role", out var role);
                                    return string.Equals(role, "Resource", StringComparison.OrdinalIgnoreCase)
                                        ? additionalText
                                        : null;
                                })
                                .WhereNotNull();

        context.RegisterSourceOutput(inputFiles, Generate);
    }

    private static void Generate(SourceProductionContext context, AdditionalText additionalText)
    {
        var inputFile = additionalText.GetText(context.CancellationToken);
        if (inputFile is null)
            return;

        var writer = new SourceWriter();
        var className = Path.GetFileNameWithoutExtension(additionalText.Path);

        writer.WriteLine("// <auto-generated />");
        writer.WriteLine();
        writer.WriteLine("using System.Globalization;");
        writer.WriteLine();
        writer.WriteLine("namespace Microsoft.AspNetCore.Razor.Language;");
        writer.WriteLine();

        var items = XDocument.Load(new StringReader(inputFile.ToString())).Descendants("data");

        writer.Write("internal static class ");
        writer.WriteLine(className);

        using (writer.BlockScope())
        {
            foreach (var item in items)
            {
                var name = item.Attribute("name")?.Value ?? string.Empty;
                var value = item.Element("value")?.Value ?? string.Empty;

                writer.Write("internal static string ");
                writer.WriteLine(name);
                writer.WriteIndent();
                writer.Write("=> ");
                writer.WriteVerbatimString(value);
                writer.WriteLine(";");
                writer.WriteLine();

                var maxParam = -1;
                foreach (Match match in Regex.Matches(value, @"\{(?<nb>[0-9]+)\}"))
                    maxParam = Math.Max(maxParam, int.Parse(match.Groups["nb"].Value));

                if (maxParam >= 0)
                {
                    var argsSb = new StringBuilder();
                    var paramsSb = new StringBuilder();

                    for (var p = 0; p <= maxParam; ++p)
                    {
                        argsSb.Append("object p").Append(p);
                        paramsSb.Append("p").Append(p);

                        if (p < maxParam)
                        {
                            argsSb.Append(", ");
                            paramsSb.Append(", ");
                        }
                    }

                    writer.Write("internal static string Format");
                    writer.Write(name);
                    writer.Write("(");
                    writer.Write(argsSb.ToString());
                    writer.WriteLine(")");
                    writer.WriteIndent();
                    writer.Write("=> string.Format(CultureInfo.InvariantCulture, ");
                    writer.Write(name);
                    writer.Write(", ");
                    writer.Write(paramsSb.ToString());
                    writer.WriteLine(");");
                    writer.WriteLine();
                }
            }
        }

        context.AddSource($"{className}.g.cs", writer.ToString());
    }
}
