//HintName: TestFile.g.cs
// <auto-generated />

namespace RazorBlade.Analyzers;

internal static partial class EmbeddedLibrary
{
    private static string TestFile => /*language=csharp*/ """
internal abstract class TestClass
{
    class InnerClass { }
    public class InnerPublicClass { }
    private class InnerPrivateClass { }

    public delegate void InnerDelegate();
}

class TestClass2 { }

internal readonly struct TestStruct { }
internal interface TestInterface { }
internal record TestRecordClass { }
internal record struct TestRecordStruct { }
internal enum TestEnum { }
internal delegate void TestDelegate();
""";
}
