//HintName: TestFile.g.cs
// <auto-generated />

namespace RazorBlade.Analyzers;

internal static partial class EmbeddedLibrary
{
    //language=csharp
    private static string TestFile => """
        // This file is part of the RazorBlade library.
        
        #nullable enable
        
        using System;
        using System.Text;
        
        internal class TestClass
        {
            [Obsolete]
            public string TestMethodA(StringBuilder sb)
                => sb.ToString();
        
            [Obsolete]
            public string TestMethodB(StringBuilder sb)
                => sb.ToString();
        
            [Obsolete]
            public string TestMethodC(StringBuilder sb)
                => sb.ToString();
        
            /// <summary>
            /// Trivia.
            /// </summary>
            public string TestMethodD(StringBuilder sb)
                => sb.ToString();
        
            /// <summary>
            /// Trivia.
            /// </summary>
            [Obsolete]
            public string TestMethodE(StringBuilder sb)
                => sb.ToString();
        }
        """;
}
