//HintName: TestFile.g.cs
// <auto-generated />

namespace RazorBlade.Analyzers;

internal static partial class EmbeddedLibrary
{
    //language=csharp
    private static string TestFile => """
        // This file is part of the RazorBlade library.
        
        #nullable enable
        
        /* #EMBEDDED# */ internal abstract class TestClass
        {
            class InnerClass { }
            public class InnerPublicClass { }
            private class InnerPrivateClass { }
        
            public delegate void InnerDelegate();
        
            protected Method() { }
            protected string Property { get; set; }
        }
        
        class TestClass2 { }
        
        /* #EMBEDDED# */ internal readonly struct TestStruct { }
        /* #EMBEDDED# */ internal interface TestInterface { }
        /* #EMBEDDED# */ internal record TestRecordClass { }
        /* #EMBEDDED# */ internal record struct TestRecordStruct { }
        /* #EMBEDDED# */ internal enum TestEnum { }
        /* #EMBEDDED# */ internal delegate void TestDelegate();
        """;
}
