//HintName: TestNamespace.TestFile.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "084db1afd162a9d0d5ed671cc7be8ca55463ec01"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : global::RazorBlade.HtmlTemplate
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\nHello, ");
#nullable restore
#line (2,9)-(2,13) 6 "./TestFile.cshtml"
Write(Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("!\r\n");
        }
        #pragma warning restore 1998
#nullable restore
#line 3 "./TestFile.cshtml"
             public string? Name { get; set; } 

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
