//HintName: TestNamespace.TestFile.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "15f9bcc8b2f02560b806b610958e0391ea4503d6"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : Foo.BaseClass
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591

// RazorSharp-specific code

#nullable restore

namespace TestNamespace
{
    partial class TestFile
    {
        public TestFile(int? foo, string? bar)
            : base(foo, bar)
        {
        }

        public TestFile(float @double, string str = "foo\\\"bar", global::System.DayOfWeek day = global::System.DayOfWeek.Friday)
            : base(@double, str, day)
        {
        }

        public TestFile(in int foo, ref int bar, out int baz, params int[] qux)
            : base(in foo, ref bar, out baz, qux)
        {
        }
    }
}
