//HintName: TestNamespace.TestFile.RazorBlade.g.cs
// <auto-generated/>

#nullable restore

namespace TestNamespace
{
    partial class TestFile<T1, T2>
    {
        /// <inheritdoc cref="M:Foo.BaseClass`1.#ctor(`0)" />
        public TestFile(T2 value)
            : base(value)
        {
        }
    }
}
