//HintName: TestNamespace.TestFile.RazorBlade.g.cs
// <auto-generated/>

#nullable restore

namespace TestNamespace
{
    partial class TestFile
    {
        /// <inheritdoc cref="M:Foo.BaseClass`1.#ctor(System.Int32)" />
        public TestFile(int value)
            : base(value)
        {
        }
    }
}
