//HintName: TestNamespace.TestFile.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8ab8d9248b0217e74bd52e7c485dabf6127571b4"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : global::RazorBlade.HtmlTemplate
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("Hello, ");
#nullable restore
#line (1,9)-(1,13) 6 "./TestFile.cshtml"
Write(Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("!\r\n");
        }
        #pragma warning restore 1998
#nullable restore
#line 2 "./TestFile.cshtml"
             public string? Name { get; set; } 

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
