//HintName: TestNamespace.TestFile.Razor.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "c919097185dd37c079d1b506881bb16d61143ae1"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : Foo.BaseClass<string>
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
        }
        #pragma warning restore 1998
#nullable restore
#line 3 "./TestFile.cshtml"
            
    internal TestFile(string value)
        : base(value)
    {
    }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
