//HintName: TestNamespace.TestFile.Razor.g.cs
#pragma checksum "./TestFile.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "112619a5e2c19c6d3e28332e1a73ba398f50e23e154af79a9bc698c33360d9c5"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : Foo.BaseClass<string>
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
        }
        #pragma warning restore 1998
#nullable restore
#line 3 "./TestFile.cshtml"
            
    internal TestFile(string value)
        : base(value)
    {
    }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
