//HintName: TestNamespace.TestFile.Razor.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "86abc6402ad4e663603e96a507949fddfacfbea7"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : global::RazorBlade.HtmlTemplate
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("TBar");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
