//HintName: TestNamespace.TestFile.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0f387a306a025bdecaddfb34c3e73317fb71c2ac"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : Foo.BaseClass
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591

#nullable restore

namespace TestNamespace
{
    partial class TestFile
    {
        /// <inheritdoc cref="M:Foo.BaseClass.#ctor(System.Int64)" />
        public TestFile(long value)
            : base(value)
        {
        }
    }
}
