//HintName: TestNamespace.TestFile.Razor.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "86f17cbd102327c60588328bdcae3f278e64fec8"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile<T1, T2> : global::RazorBlade.HtmlTemplate
    where T2 : struct
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("Hello, ");
#nullable restore
#line (3,9)-(3,19) 6 "./TestFile.cshtml"
Write(typeof(T1));

#line default
#line hidden
#nullable disable
            WriteLiteral(" and ");
#nullable restore
#line (3,25)-(3,35) 6 "./TestFile.cshtml"
Write(typeof(T2));

#line default
#line hidden
#nullable disable
            WriteLiteral("!\r\n");
#nullable restore
#line (4,2)-(4,26) 6 "./TestFile.cshtml"
Write(NeedsStruct(default(T2)));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n\r\n");
        }
        #pragma warning restore 1998
#nullable restore
#line 6 "./TestFile.cshtml"
            
    T NeedsStruct<T>(T value) where T : struct => value;

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
