//HintName: TestNamespace.TestFile.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4278210359971b69dd6e8b9c3609cde040248acc"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : global::RazorBlade.HtmlTemplate
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("Hello, <a");
            BeginWriteAttribute("href", " href=\"", 9, "\"", 21, 1);
#nullable restore
#line (1,17)-(1,22) 28 "./TestFile.cshtml"
WriteAttributeValue("", 16, Link, 16, 5, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">World</a>!\r\n");
        }
        #pragma warning restore 1998
#nullable restore
#line 2 "./TestFile.cshtml"
             public string? Link { get; set; } 

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
