//HintName: TestNamespace.TestFile.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "d7099b16b188ca93e7cdfa6b520cd00c715c02a6"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : global::RazorBlade.HtmlTemplate
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\nHello, <a");
            BeginWriteAttribute("href", " href=\"", 11, "\"", 23, 1);
#nullable restore
#line (2,17)-(2,22) 28 "./TestFile.cshtml"
WriteAttributeValue("", 18, Link, 18, 5, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">World</a>!\r\n");
        }
        #pragma warning restore 1998
#nullable restore
#line 3 "./TestFile.cshtml"
             public string? Link { get; set; } 

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
