//HintName: TestNamespace.TestFile.Razor.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "c5ddc67791758895b8ee73dd2a45225d3418acdb"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : global::RazorBlade.HtmlTemplate
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("Before section\r\n");
            DefineSection("SectionName", async() => {
                WriteLiteral(" Section content ");
            }
            );
            WriteLiteral("After section\r\n");
            DefineSection("OtherSectionName", async() => {
                WriteLiteral(" Answer is ");
#nullable restore
#line (4,41)-(4,43) 6 "./TestFile.cshtml"
Write(42);

#line default
#line hidden
#nullable disable
                WriteLiteral(" ");
            }
            );
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
