//HintName: TestNamespace.TestFile.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6d6766ee762b347c749be1e90506e83434dcb8b4"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
#nullable restore
#line 1 "./TestFile.cshtml"
using System;

#line default
#line hidden
#nullable disable
    #nullable restore
    internal partial class TestFile : RazorBlade.HtmlTemplate<Tuple<DateTime, string?>>
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
        }
        #pragma warning restore 1998

        #nullable restore

        /// <inheritdoc cref="M:RazorBlade.HtmlTemplate`1.#ctor(`0)" />
        public TestFile(global::System.Tuple<global::System.DateTime, string?> model)
            : base(model)
        {
        }
    }
}
#pragma warning restore 1591
