//HintName: TestNamespace.TestFile.Razor.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0807084d82613f0723fcf8cbf13b9150a8336425"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
#nullable restore
#line 1 "./TestFile.cshtml"
using System.Collections.Generic;

#line default
#line hidden
#nullable disable
    #nullable restore
    internal partial class TestFile : global::RazorBlade.HtmlTemplate
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
        }
        #pragma warning restore 1998
#nullable restore
#line 3 "./TestFile.cshtml"
 
    public partial string Name { get; }
    public partial string Name => "Foo";

    public T Foo<T>(T value) where T : allows ref struct => value;
    public string Foo<T>(params IEnumerable<T> values) => "a\eb";

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
