//HintName: TestNamespace.TestFile.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9bf59f868e492f9c38ba944f8730baf21d670178"
// <auto-generated/>
#pragma warning disable 1591
namespace CustomNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : global::RazorBlade.HtmlTemplate
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
