//HintName: TestNamespace.TestFile.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5680128789ad7f88c183c8785ada06daca186464"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
#nullable restore
#line 3 "./TestFile.cshtml"
using System.Threading.Tasks;

#line default
#line hidden
#nullable disable
    #nullable restore
    internal partial class TestFile : Foo.BaseClassC
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line (4,2)-(4,27) 6 "./TestFile.cshtml"
Write(await Task.FromResult(42));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591

// RazorBlade-specific code

#nullable restore

namespace TestNamespace
{
    partial class TestFile
    {
        /// <inheritdoc cref="M:Foo.BaseClassC.OnlyOnSync(System.Int32)" />
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Obsolete("Hello, world!", DiagnosticId = "RB0003")]
        public new void OnlyOnSync(int i)
            => base.OnlyOnSync(i);

        /// <inheritdoc cref="M:Foo.BaseClassC.OnlyOnSync(System.Double)" />
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Obsolete("Hello, double", DiagnosticId = "RB0003")]
        public new void OnlyOnSync(double i)
            => base.OnlyOnSync(i);

        /// <inheritdoc cref="M:Foo.BaseClassB.SomeParams(System.Single,System.String,System.DayOfWeek)" />
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Obsolete("Hello", DiagnosticId = "RB0003")]
        public new void SomeParams(float @double, string? str = "foo\\\"bar", global::System.DayOfWeek day = global::System.DayOfWeek.Friday)
            => base.SomeParams(@double, str, day);

        /// <inheritdoc cref="M:Foo.BaseClassB.SomeParams(System.Int32@,System.Int32@,System.Int32@,System.Int32[])" />
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Obsolete("\\\"\\", DiagnosticId = "RB0003")]
        public new void SomeParams(in int foo, ref int bar, out int baz, params int[] qux)
            => base.SomeParams(in foo, ref bar, out baz, qux);

        /// <inheritdoc cref="M:Foo.BaseClassA`1.Generic(`0)" />
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Obsolete("Hello!", DiagnosticId = "RB0003")]
        public new void Generic(string i)
            => base.Generic(i);

        /// <inheritdoc cref="M:Foo.BaseClassA`1.Generic``2(`0,``0)" />
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Obsolete("Hello!", DiagnosticId = "RB0003")]
        public new void Generic<TValueA, @int>(string i, TValueA j)
            => base.Generic<TValueA, @int>(i, j);
    }
}
