//HintName: TestNamespace.TestFile.Razor.g.cs
#pragma checksum "./Path/Dir/TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "1a741609900d6039a8ff571fa06e65cb20525043"
// <auto-generated/>
#pragma warning disable 1591
namespace OverridenNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : global::RazorBlade.HtmlTemplate
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("Hello");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
