//HintName: TestNamespace.TestFile.Razor.g.cs
#pragma checksum "./TestFile.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "e3ef1fb2f0884999ec2cb696320bd59e3a3cb5465648217ab5affee56f531844"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : global::RazorBlade.HtmlTemplate
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("Hello, ");
#nullable restore
#line (1,9)-(1,13) 6 "./TestFile.cshtml"
Write(Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("!\r\n");
        }
        #pragma warning restore 1998
#nullable restore
#line 2 "./TestFile.cshtml"
             public string? Name { get; set; } 

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
