//HintName: TestNamespace.TestFile.Razor.g.cs
#pragma checksum "./TestFile.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5068ff86d7f99fd308a3dc90ef5abec8f77a25fae20538fa00e6e8fa786cd055"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : Foo.BaseClass
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
        }
        #pragma warning restore 1998
#nullable restore
#line 3 "./TestFile.cshtml"
            
    internal TestFile(ref int value)
        : base(value)
    {
    }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
