//HintName: TestNamespace.TestFile.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "cbe0a906e44a592f77ff14bc5383811edc9236e9"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : Foo.BaseClass
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
        }
        #pragma warning restore 1998
#nullable restore
#line 3 "./TestFile.cshtml"
            
    internal TestFile(ref int value)
        : base(value)
    {
    }

#line default
#line hidden
#nullable disable

        #nullable restore

        /// <inheritdoc cref="M:Foo.BaseClass.#ctor(System.Int32)" />
        public TestFile(int value)
            : base(value)
        {
        }

        /// <inheritdoc cref="M:Foo.BaseClass.#ctor(System.String)" />
        public TestFile(string value)
            : base(value)
        {
        }
    }
}
#pragma warning restore 1591
