//HintName: TestNamespace.TestFile.RazorBlade.g.cs
// <auto-generated/>

#nullable restore

namespace TestNamespace
{
    partial class TestFile
    {
        /// <inheritdoc cref="M:Foo.BaseClass.#ctor(System.Int64)" />
        public TestFile(long value)
            : base(value)
        {
        }
    }
}
