//HintName: TestNamespace.TestFile.Razor.g.cs
#pragma checksum "./Path/Dir/TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "f7ff9e8b7bb2e09b70935a5d785e0cc5d9d0abf0"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : CorrectBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("Hello");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
