<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <EnableNUnitRunner>true</EnableNUnitRunner>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../RazorBlade/RazorBlade.csproj" />
    <ProjectReference Include="../RazorBlade.Analyzers/RazorBlade.Analyzers.csproj" />
    <ProjectReference Include="../RazorBlade.MetaAnalyzers/RazorBlade.MetaAnalyzers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" NoWarn="NU1608" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Verify.DiffPlex" />
    <PackageReference Include="Verify.NUnit" />
    <PackageReference Include="Verify.SourceGenerators" />
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../RazorBlade.Library.Tests/Support/AssertExtensions.cs" Link="Support/%(Filename)%(Extension)" />
  </ItemGroup>

  <!-- netstandard2.0 -->

  <ItemGroup>
    <ProjectReference Include="../RazorBlade/RazorBlade.csproj" SetTargetFramework="TargetFramework=netstandard2.0" OutputItemType="RazorBladeNetStdRef" ReferenceOutputAssembly="false" />
    <PackageReference Include="NETStandard.Library" VersionOverride="2.0.3" IncludeAssets="none" GeneratePathProperty="true" />
    <RazorBladeNetStdRef Include="$(PkgNETStandard_Library)/build/netstandard2.0/ref/netstandard.dll" Visible="false" />
  </ItemGroup>

  <Target Name="RazorBladeCopyNetStdRef" BeforeTargets="AssignTargetPaths">
    <ItemGroup>
      <None Include="@(RazorBladeNetStdRef)" CopyToOutputDirectory="PreserveNewest" Link="netstandard/%(Filename)%(Extension)" />
    </ItemGroup>
  </Target>

</Project>
