//HintName: TestNamespace.TestFile.Razor.g.cs
#pragma checksum "./TestFile.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "92997f92111e43efc000fb3b5ddd05bc80288c63f1d60041af22993b3147c7ca"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
#nullable restore
#line 1 "./TestFile.cshtml"
using System;

#line default
#line hidden
#nullable disable
    #nullable restore
    internal partial class TestFile : RazorBlade.HtmlTemplate<Tuple<DateTime, string?>>
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
