//HintName: TestNamespace.TestFile.Razor.g.cs
#pragma checksum "./TestFile.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5dcfafe78add9a7a23b81d04e532e290520470e8d67ad578aeea73cb4129eb98"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : global::RazorBlade.HtmlTemplate
    #nullable disable
    {
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
