//HintName: TestNamespace.TestFile.Razor.g.cs
#pragma checksum "./TestFile.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7d1bf96c7a620fb1dd952bb5c2f5496163205235"
// <auto-generated/>
#pragma warning disable 1591
namespace TestNamespace
{
    #line hidden
    #nullable restore
    internal partial class TestFile : global::RazorBlade.HtmlTemplate, global::RazorBlade.ITagHelperTemplate
    #nullable disable
    {
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(__tagHelperHandler.StartTagHelperWritingScope, __tagHelperHandler.EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        #pragma warning disable 0649
        private global::RazorBlade.TagHelperHandler __backed__tagHelperHandler;
        #pragma warning restore 0649
        private global::RazorBlade.TagHelperHandler __tagHelperHandler => __backed__tagHelperHandler ??= new global::RazorBlade.TagHelperHandler(this);
        private global::BoldTagHelper __BoldTagHelper;
        #pragma warning disable 1998
        protected async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\nHello, ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("span", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "7d1bf96c7a620fb1dd952bb5c2f54961632052352239", async() => {
                WriteLiteral("this should be in bold.");
            }
            );
            __BoldTagHelper = __tagHelperHandler.CreateTagHelper<global::BoldTagHelper>();
            __tagHelperExecutionContext.Add(__BoldTagHelper);
            __tagHelperHandler.BeginWriteTagHelperAttribute();
            __tagHelperStringValueBuffer = __tagHelperHandler.EndWriteTagHelperAttribute();
            __tagHelperExecutionContext.AddHtmlAttribute("bold", __tagHelperHandler.HtmlRaw(__tagHelperStringValueBuffer), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.Minimized);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            __tagHelperHandler.Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
